# Site settings
name: Ben Ripkens
title: Ben's blog
email: bripkens.dev@gmail.com
description: ""
baseurl: ""
url: "http://blog.bripkens.de"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title

# The tag cloud plugin cannot be used on GitHub. Deactivate tag links
# until GitHub pages supports such a plugin
showTagLinks: false
